name: 'cancer_screening_analytics'
version: '1.0.0'
config-version: 2

profile: 'cancer_screening_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cancer_screening_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +schema: intermediate
      
      core:
        +materialized: table
        +schema: intermediate
        fct_screenings:
          +materialized: incremental
          +unique_key: screening_key
        fct_screening_journey:
            +materialized: incremental
            +unique_key: journey_key
    marts:
      +materialized: table
      +schema: marts
      
      client_analytics:
        +materialized: table
        +schema: marts
      
      internal_ops:
        +materialized: table
        +schema: marts

seeds:
  cancer_screening_analytics:
    +schema: raw
    +quote_columns: false

tests:
  +severity: error
  
flags:
  require_generic_test_arguments_property: true