name: 'cancer_screening_analytics'
version: '1.0.0'
config-version: 2

profile: 'cancer_screening_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cancer_screening_analytics:
    staging:
      +materialized: view
      +schema: staging
    core:
      +materialized: table
      +schema: intermediate
      fct_screenings:
        +materialized: incremental
        +unique_key: screening_key
        +partition_by:
            field: screening_date
            data_type: date
        +cluster_by: ["member_key", "screening_type"]
        
      agg_member_enrollment_summary:
          +materialized: table
          +unique_key: member_key
          +partition_by:
            field: enrollment_date
            data_type: date
          +cluster_by: ["employer_key", "enrollment_status"]
    marts:
      +materialized: table
      +schema: marts
      
      client_analytics:
        +materialized: table
        +schema: marts
      
      internal_ops:
        +materialized: table
        +schema: marts

seeds:
  cancer_screening_analytics:
    +schema: raw
    +quote_columns: false

tests:
  +severity: error
  
flags:
  require_generic_test_arguments_property: true