version: 2

sources:
  - name: raw
    description: "Raw data loaded from CSV seeds representing Color's cancer screening program data"
    database: "{{ target.project }}"
    schema: "{{ 'dbt_mvargas_raw' if target.name == 'default' else target.schema + '_raw' }}"
    tables:
      - name: raw_members
        description: |
          Raw member (patient) data from Color's screening program. Contains demographic information,
          contact details, and risk flags for individuals enrolled in employer-sponsored cancer screening.
          Each row represents one unique member/patient.
        columns:
          - name: member_id
            description: "Unique identifier for each member/patient in the screening program"
            tests:
              - unique
              - not_null
          - name: employer_id
            description: "Foreign key to employers table - identifies which company/organization sponsors this member"
            tests:
              - not_null
          - name: date_of_birth
            description: "Member's date of birth, used to calculate age and determine screening eligibility"
            tests:
              - not_null
          - name: gender
            description: "Member's gender (M/F/Other), affects screening type eligibility (e.g., mammograms for women)"
            tests:
              - accepted_values:
                  values: ['M', 'F', 'Other']
          - name: email
            description: "Member's email address for outreach and results delivery. May contain nulls (~2%) for data quality testing."
          - name: high_risk_flag
            description: "Boolean flag indicating member has elevated cancer risk factors (family history, genetic markers, etc.)"
          - name: created_at
            description: "Timestamp when member record was first created in the system"
      
      - name: raw_employers
        description: |
          Employer/client organizations that sponsor cancer screening programs for their employees.
          Each row represents one company/organization that has contracted with Color for screening services.
          Used to segment program performance by client and track contract details.
        columns:
          - name: employer_id
            description: "Unique identifier for each employer/client organization"
            tests:
              - unique
              - not_null
          - name: employer_name
            description: "Company/organization name"
          - name: industry
            description: "Industry sector (Technology, Healthcare, Manufacturing, etc.) - used for benchmarking"
          - name: employee_count
            description: "Total number of employees at organization - represents eligible screening population"
          - name: state
            description: "Primary state where employer operates - used for geographic analysis"
          - name: contract_start_date
            description: "Date when employer's contract with Color began"
      
      - name: raw_enrollments
        description: |
          Program enrollment records tracking when members sign up for cancer screening services.
          Each row represents one member's enrollment in their employer's screening program.
          Tracks enrollment channel (how they signed up) and current status (active/completed/inactive).
        columns:
          - name: enrollment_id
            description: "Unique identifier for each enrollment record"
            tests:
              - unique
              - not_null
          - name: member_id
            description: "Foreign key to members - identifies which member is enrolling"
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'raw_members')
                  field: member_id
          - name: enrollment_date
            description: "Date when member enrolled in the screening program"
          - name: enrollment_channel
            description: "How member enrolled: Email, Portal, Phone, or HR Event - used to optimize outreach strategies"
            tests:
              - accepted_values:
                  values: ['Email', 'Portal', 'Phone', 'HR Event']
          - name: status
            description: "Current enrollment status: Active (ongoing), Completed (finished program), or Inactive (dropped out)"
            tests:
              - accepted_values:
                  values: ['Active', 'Completed', 'Inactive']
          - name: consent_given
            description: "Boolean flag confirming member provided informed consent for screening"
      
      - name: raw_screenings
        description: |
          Cancer screening events - the core fact table of the program. Each row represents one completed
          screening procedure (mammogram, colonoscopy, etc.) with results and follow-up requirements.
          This is the primary data used to measure program effectiveness and clinical outcomes.
        columns:
          - name: screening_id
            description: "Unique identifier for each screening procedure"
            tests:
              - unique
              - not_null
          - name: member_id
            description: "Foreign key to members - identifies which member received the screening"
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'raw_members')
                  field: member_id
          - name: screening_type
            description: "Type of cancer screening: Mammogram, Colonoscopy, Prostate Screening, Cervical Screening, etc."
            tests:
              - accepted_values:
                  values: ['Mammogram', 'Colonoscopy', 'Prostate Screening', 'Cervical Screening', 'General Health Screening']
          - name: screening_date
            description: "Date when screening procedure was performed"
          - name: result
            description: "Screening result: Normal (no issues), Abnormal - Benign (requires follow-up), or Cancer Detected"
            tests:
              - accepted_values:
                  values: ['Normal', 'Abnormal - Benign', 'Cancer Detected']
          - name: result_date
            description: "Date when screening results were delivered to member"
          - name: follow_up_needed
            description: "Boolean flag indicating whether abnormal result requires follow-up care"
          - name: follow_up_completed
            description: "Boolean flag indicating whether required follow-up was completed (null if no follow-up needed)"
          - name: cost
            description: "Cost of screening procedure in dollars"
      
      - name: raw_providers
        description: |
          Healthcare providers (physicians, clinics) who perform cancer screenings for Color members.
          Each row represents one provider with their specialty and credentials.
          Used to analyze provider performance and network adequacy.
        columns:
          - name: provider_id
            description: "Unique identifier for each healthcare provider"
            tests:
              - unique
              - not_null
          - name: provider_name
            description: "Provider's name (e.g., Dr. Smith)"
          - name: specialty
            description: "Provider's medical specialty: Radiology, Oncology, Primary Care, Gastroenterology, Pathology"
            tests:
              - accepted_values:
                  values: ['Radiology', 'Oncology', 'Primary Care', 'Gastroenterology', 'Pathology']
          - name: npi_number
            description: "National Provider Identifier - unique 10-digit ID for healthcare providers in the US"

      - name: raw_followup_predictions
        description: "Logistic regression model predictions for follow-up completion likelihood"